name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 작업사항'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 버그 수정사항'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (PR: #$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
      - 'release: GA'
  minor:
    labels:
      - 'minor'
      - 'release: RC'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## 작업사항 (Content)

  $CHANGES
